name: nian_beast
version: '0.1.0-am9'
main: com.wenkrang.nian_beast.NianBeast
api-version: '1.20.5'
libraries:
  - "org.scala-lang:scala-library:2.10.7"
commands:
  nb:
    description: 年兽 插件的主命令
    usage: /nb